---
title: Croasan
timezone: UTC
collections:
  diaries:
    title: Diaries
    output: true
    permalink: "/:collection/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: A photo diary.
baseurl: "/croasan"
url: http://croasan.github.io
twitter_username: croasan
github_username: croasan
theme: minima
plugins:
- jekyll-feed
