---
title: Croasan
timezone: UTC
collections:
collections:
  tags:
    output: true
    permalink: tag/:title/
  diaries:
    title: Diaries
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: A photo diary.
baseurl: "/"
url: https://croasan.github.io
twitter_username: croasan
github_username: croasan
theme: minima
plugins:
- jekyll-feed
defaults:
  -
    scope:
      path: ""
      type: tags
    values:
      layout: tag
